name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # Runs daily at midnight UTC
  workflow_dispatch:        # Allow manual run

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Allows pushing to branches
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: Muthuraj-coder
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      - name: Prepare Output Branch
        run: |
          # Create output directory before switching branch
          mkdir -p output
          cp dist/* output/

          # Switch to orphan branch
          git fetch origin
          git checkout --orphan output
          git rm -rf .
          mv output/* ./
          git add *
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Generate Snake Animation"
          git push origin output --force
